export const SAMPLE_TEXT = [
    {type: "h1", content: "Google Pixel phones to be unveiled October 4"},
    {type: "h2", content: "The firm may also launch its voice-activated AI home audio speaker, a VR headset and a 4K Chromecast"},
    {type: "p", content: "Google will unveil its latest Pixel smartphones on October 4, the firm has suggested through a teaser website."},
    {type: "p", content: "It is believed the Nexus brand name will be dropped in favour of two new models: the Pixel and the Pixel XL."},
    {type: "p", content: "Current rumours around the devices – which have been codenamed Sailfish and Marlin – say the devices will be 5-inch and 5.5-inch phones. At Google's developer conference in May CEO Sundar Pichai hinted that the new line would includes additional Google features built on top of the Android operating system. As such, Pixel is expected to become a premium brand."},
    {type: "p", content: "The teaser website shows a search bar that morphs into the outline of a phone, before flashing with various images. The event will take place in San Francisco at 9AM PST (5PM BST), and be streamed on YouTube."},
    {type: "a", content: "Leaked images of the Pixel phones", href: "http://www.wired.co.uk/gallery/google-pixel-phone-pictures"},
    {type: "a", content: "Leaked images of the Pixel phones"},
    {type: "a", content: "Android Police"},
    {type: "p", content: "At present the company controls the design and marketing of its Nexus products, with the manufacturing of the devices outsourced to third parties. This, according to Pichai earlier this year, will not change."},
    {type: "p", content: "But there could also be more to come from the event. A previous report from Android Police has said the event will be packed with Google's latest products."},
    {type: "p", content: "Rumoured to be launching that day will be a Google virtual reality headset, under the guise of the Google Daydream project; a 4K Chromecast, and its highly anticipated AI personal assistant device."},
    {type: "p", content: "At its developer conference, Google announced a new voice-controlled, artificial intelligence Home speaker that will connect to devices around a building and be able to control them."},
    {type: "a", content: "The artificial intelligence based Google Home speaker"},
    {type: "a", content: "The artificial intelligence based Google Home speaker"},
    {type: "a", content: "Google", href: "http://www.google.com"},
    {type: "p", content: "The device will use a Google Assistant, which is being built into a new Google messages app called Allo – which is rumoured to be launching before the October event. 'With a simple voice command, you can ask Google Home to play a song, set a timer for the oven, check your flight, or turn on your lights,' the firm said at the time."},
    {type: "p", content: "Any home device would be a rival to Amazon's Echo, which launched in the UK on September 16. The Echo uses Amazon's own personal assistant, Alexa, to control internet of things devices as well as provide news, weather, and travel updates."},
    {type: "p", content: "Although the teaser website doesn't reference any of these products, Google previously said its Home device would launch before the end of 2016."},
];
